language: ruby
script : script/cibuild
rvm:
- 2.2
- 2.1
- 2.0
notifications:
  email: false


matrix:
  include:
    -
      rvm: 1.9
      env: JEKYLL_VERSION=2.0
env:
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
